In [70]:
import pandas as pd

In [71]:
df = pd.read_csv("train.csv", encoding="latin1")

In [72]:
df.shape

(9800, 18)

In [73]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [74]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [75]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales']

In [76]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

## ¿Cuál es la categoría de producto que más ventas genera en total?

In [78]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

## ¿Cuál es la media de ventas por Region y Category a la vez?

In [79]:
df.groupby(["Region","Category"])["Sales"].mean()

Region   Category
Central  Furniture          341.100983
         Office Supplies    116.933698
         Technology         413.576490
East     Furniture          349.342450
         Office Supplies    119.940499
         Technology         499.272347
South    Furniture          357.458528
         Office Supplies    126.576573
         Technology         512.786187
West     Furniture          355.062584
         Office Supplies    116.917478
         Technology         420.042326
Name: Sales, dtype: float64

## ¿Cuántos pedidos distintos hay por Region?

In [80]:
df.groupby("Region")["Order ID"].nunique()

Region
Central    1156
East       1369
South       810
West       1587
Name: Order ID, dtype: int64

## Convertir 'Orden Date' de string a fecha

In [81]:
df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True)

In [82]:
df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date                   str
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code             float64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
dtype: object

In [83]:
df.shape

(9800, 18)

## ¿Cuáles son las ventas totales por año?

In [88]:
df.groupby(df["Order Date"].dt.year)["Sales"].sum()

Order Date
2015    479856.2081
2016    459436.0054
2017    600192.5500
2018    722052.0192
Name: Sales, dtype: float64

## ¿Cuántas ventas de media por cada mes del año?

In [98]:
df.groupby(df["Order Date"].dt.month)["Sales"].mean().sort_values(ascending=False)

Order Date
3     290.549393
1     257.627403
10    246.596162
11    241.657496
12    232.619515
8     227.007110
9     221.642106
5     212.533412
6     211.052856
7     208.802997
4     207.432269
2     199.902745
Name: Sales, dtype: float64

In [92]:
df.groupby([df["Order Date"].dt.year, df["Order Date"].dt.month])["Sales"].sum()

Order Date  Order Date
2015        1              14205.7070
            2               4519.8920
            3              55205.7970
            4              27906.8550
            5              23644.3030
            6              34322.9356
            7              33781.5430
            8              27117.5365
            9              81623.5268
            10             31453.3930
            11             77907.6607
            12             68167.0585
2016        1              18066.9576
            2              11951.4110
            3              32339.3184
            4              34154.4685
            5              29959.5305
            6              23599.3740
            7              28608.2590
            8              36818.3422
            9              63133.6060
            10             31011.7375
            11             75249.3995
            12             74543.6012
2017        1              18542.4910
            2              22978.8150
            3              51165.0590
            4              38679.7670
            5              56656.9080
            6              39724.4860
            7              38320.7830
            8              30542.2003
            9              69193.3909
            10             59583.0330
            11             79066.4958
            12             95739.1210
2018        1              43476.4740
            2              19920.9974
            3              58863.4128
            4              35541.9101
            5              43825.9822
            6              48190.7277
            7              44825.1040
            8              62837.8480
            9              86152.8880
            10             77448.1312
            11            117938.1550
            12             83030.3888
Name: Sales, dtype: float64

## ¿Cuántos pedidos hay de cada tipo de envío (Ship Mode)?

In [104]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: count, dtype: int64